### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by noto-alex-j** [noto-alex-j/OO-music-inventory#2]
This simple schema should contain all of the information represented in the original project.

https://docs.google.com/spreadsheets/d/1g07JQ7H5SARKpC5mBZ8C_W-dDpbAVSCaoplaBnzxb68/edit#gid=0

**Comment by sumeetjain** [comment]
Consider defining a table for Artists as well, so you can reference `artist_id` in your Albums table instead of explicitly defining the artists.

Otherwise, 👍

**Comment by noto-alex-j** [comment]
Will do, thanks!
