### ISSUE TITLE
Linking tables when creating entries

### ISSUE THREAD

**Issue by noto-alex-j** [noto-alex-j/OO-music-inventory#3]
I don't have a specific code problem as much as a planning question. I've defined my classes in this model: https://github.com/noto-alex-j/OO-music-inventory/blob/master/app/models/classes.rb
Each class has a respective table. I understand how the tables are linked together by their entry IDs, but when inserting, say, a new song, the instance of the Song class is initialized with the relevant albumid. The user can put the album *name* in via form submission when entering the new song, but they won't know what that album's ID is in the database, of course. Do I use the album name from the form submission and use an Album.find method with the album name as the argument, to look up the album_id? What if there are two albums with the same name? I've written an Artist.find method, would I use something like this when getting the artistid for creating a new Album instance? I'm trying to understand how to link these three tables together as a user enters information into the database.

**Comment by halfghaninne** [comment]
Am I understanding that, in this case the User is creating new Songs **and** a new Album? Or are they adding Songs to an existing Album?

**Comment by noto-alex-j** [comment]
In the original design, the user added songs as the primary form of input. The artist and album information were within the song input form. I imagined that here, they could choose to input either a song, and album, or an artist. But even if, say, I only allowed them to input individual songs, how would I link that song with the relevant album, and then link the album with the relevant artist? Does my question make sense?

**Comment by halfghaninne** [comment]
I think so. I'm taking it to mean the Songs will be linked with an Artist and Album that already exist in the database. 

Ideally there will be some form element (like a drop down) for song input that display meaningful options to the User (Artist or Album names), but have an actual value of that Artist or Album's ID. 

That might look something like:
```html
<select>
  <option value="1">Some Album Title</option>
  <option value="2">Some Album Title</option>
</select>
```

Note that -- though the album titles displayed in the option tags are the same, their values/IDs are different.

**Comment by noto-alex-j** [comment]
The dropdown menu would definitely be an option, but it seems that the list would become increasingly longer, the more artists and albums there are in the database. Perhaps I could attempt some sort of JavaScript search field that would search the database for existing artists/albums as they're typing? I'm not sure how complex that would be. If the artist/album does not already exist in the database, then I could just create it as the song is added?

**Comment by sumeetjain** [comment]
The assignment is not to add or even change the functionality of the projects. It is specifically to convert the existing codebase to use a more ORM-like implementation of classes for database connection. You're right that the dropdown would become unwieldy, but that’s fine for now.

A question though: Why was this not a problem in the original build of the project? How was it implemented before? It should be the same implementation this time around.

---

If you feel like this assignment negates the use of ORMs, that's something we can dig into. (And perhaps you and Alex might like to work together for a bit after lunch.) But I urge you to stick as closely to keeping the feature set the same and just replacing old methods with newer ORM methods.

**Comment by noto-alex-j** [comment]
The original build used flat-file storage, and songs were input individually. An entry would look like songtitle||artist||album||genre||lengthmin||lengthsec||albumrating||songrating. I could easily split each line into an array and then search each line for an artist name or album name. Songs were linked as multiple songs would have the same artist or album, so all songs with matching information would be returned when searching by artist or album. It didn't matter if an artist or album had or had not been previously entered into the flat file. Once a song was entered, that artist and album were included by virtue of the format of the song input.  I'm not trying to add to or change the functionality of the project. But now the song, artist, and album information are split among three linked tables. It would seem that to input a song by, say, Led Zeppelin, Led Zeppelin and the relevant album would already need to exist in the table. If so, their requisite IDs would need to be looked up to link everything together. If not, they'd have to be created first. The only way I can see to retain the same functionality as the original build is to have one table for songs, with ID, Title, Artist, Album, Genre, Length, and Rating as fields.

**Comment by sumeetjain** [comment]
Gotcha. That clarifies things a bit.

I still see the form submission working as it did previously. So a single form for collecting song information, including the title of the artist and the album.

That form then submits to, let's say, `MyApp.post "/songs/create"`. That controller action processes the submission by running this:

```ruby
@song = Song.create_with_album_and_artist(params["songtitle"], params["artist"], params["album"], params["genre"]) # There would be more params, I imagine–but you get the idea.
```

The `Song` model then needs to have a class method called `create_with_album_and_artist`. Pseudo-code for it:

```ruby
def self.create_with_album_and_artist(title, artist, album, genre)
  # check if artist exists. if it doesn't create it, capture its ID in a local var. if it does, capture its ID in a local var.

  # same for album

  # add a new song to the DB, using the foreign key values we just set.
  # return the newly added song as a `Song` object.
end
```

Let me know if this helps clear things up. This is a complicated feature! 😬  :)

**Comment by noto-alex-j** [comment]
Yes, I haven't yet modified the original form, but it should work pretty similarly. That helps clear it up a lot. I'll stick with using the song to input information, and the artist and album information will be added as a result of inputting song information. Thanks!
