### ISSUE TITLE
No test results

### ISSUE THREAD

**Issue by noto-alex-j** [noto-alex-j/OO-music-inventory#4]
I wrote a simple test to check instance creation, just to get my tests working. When I run 'bundle exec rake test' in my terminal, nothing is output to the terminal. There don't seem to be any errors, there is just no output. The coverage file gives me a percentage though. Also, my coverage folder only contains one file. 

Expected:
Run 'bundle exec rake test'
Results output to terminal
Actual:
Nothing

**Comment by halfghaninne** [comment]
Your Rakefile is [looking for]( t.pattern = 'tests/**/*_test.rb') test files that end in _test.rb. Changing your file name should result in seeing some output in the command line!

**Comment by noto-alex-j** [comment]
Ohhhhh. Wow that was a super easy fix. Thank you!
